### ISSUE TITLE
styles.css is not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#11]
the styles.css files are all combined and cached by moodle in a single file - this means that you must be very specific when defining styles.

All styles that target content that displays inside the block should be prefixed with:
.block_socialcomments

For your extra files (like those in report folder) - Moodle should add the class path-
block_socialcomments automatically to the body class so you could use that to target css on these files.

for example in your css you have classes like this defined:
```
.fullwidth {
    width : 95%;
}
```
That could conflict with anything else in the site with a "fullwidth" css tag and should be either:
```
.block_socialcomments .fullwidth {
    width : 95%;
}
```
or:
```
.path-block_socialcomments .fullwidth {
    width : 95%;
}
```

**Comment by danmarsden** [comment]
FYI - this also includes your more specific classes like "ccomments-pin-tooltip" - all of them must be prefixed in your styles.css with .block_socialcomments or .path-block_socialcomments

**Comment by annebardtke** [comment]
done
