### ISSUE TITLE
code precheck failures

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#12]
Warning Maturity information ($plugin->maturity) not found in version.php

Also would be good for you to review the precheck reports that Moodle provides:
https://moodle.org/plugins/pluginversion.php?id=17930

You are not required to fix all the code precheck issues but it does give a nice Green "passed" image on your plugin entry when they are passing :-)

**Comment by annebardtke** [comment]
done
