### ISSUE TITLE
invalid table names

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#3]
tables should be prefixed with the frankenstyle prefix - you have used "block_scomments" but this should be "block_socialcomments" - this is quite a critical issue because Moodle uninstall processes will not work correctly for your block and your tables could conflict if someone creates a "scomments" block and runs an uninstall (which would delete the tables in your block as well.)

**Comment by paulsteffen** [comment]
Table names fixed. Added `db/upgrade.php` with upgrade instructions.

**Comment by annebardtke** [comment]
done
