### ISSUE TITLE
invalid use of Moodle database apis

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#4]
https://github.com/Elearning-HWR-Berlin/moodle-block_social-comments/blob/master/classes/local/basepost.php#L46

when calling db functions, you shouldn't be storing your "tablename" in another variable and passing it through. The Tablename is vulnerable to SQL injection and it should be obvious to a reviewer that there is no sql injection possible when looking at a database function.

Ideally you should rewrite this so that the tablename is hard-coded in the get_record() call instead of in a parameter passed via another script.

**Comment by paulsteffen** [comment]
Fixed by changes in commit 1d0ece5cfa89f2f95c7f3bdb958335660654ef0d, (pr #14)

**Comment by annebardtke** [comment]
done
