### ISSUE TITLE
report_helper.php.dist

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#6]
in classes/local/ - guessing that's a backup file that should be cleaned up/removed :-)

**Comment by danmarsden** [comment]
also renderer.php.dist - guessing that needs to be removed too.

**Comment by danmarsden** [comment]
..and styles.css.dist

**Comment by paulsteffen** [comment]
report_helper.php.dist, renderer.php.dist and styles.css.dist removed by pr #14 
no other orphaned files found

**Comment by annebardtke** [comment]
done
