### ISSUE TITLE
task scheduled at midnight.

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#8]
It might be nicer for you to use "R" instead of "0" in your minute and hour fields which causes a random value to be set in the database at install time.
More info on this is here:
https://docs.moodle.org/dev/Task_API#Scheduled_task_usage

It's common for the server to have a lot of tasks scheduled at 0:00 - it's nice if you can stagger these a little bit by setting a random value instead.

**Comment by paulsteffen** [comment]
Setting random value at install time as advised.

**Comment by annebardtke** [comment]
done
