### ISSUE TITLE
Camel case

### ISSUE THREAD

**Issue by danmarsden** [Elearning-HWR-Berlin/moodle-block_social-comments#9]
$string['socialcomments:viewreport'] = 'View Report';
$string['reportspage'] = 'Comments Report';
$string['taballcomments'] = 'All Comments';
$string['tabnewcomments'] = 'New Comments';

Standard Moodle convention only capitilises the first word - you should review your language strings and tidy these up.

**Comment by paulsteffen** [comment]
Language strings changed to match the Moodle convention.

**Comment by annebardtke** [comment]
done
